<nav:bar 0     main "">
 <nav:but welcome        "Welcome"                 index                         />
 <nav:but down           "Download"                download                      />
 <nav:but license        "License"                 license                       />
 <nav:but demo           "Demo"		           http://www.stat.ee.ethz.ch/mrtg/  />
 <nav:but doc            "Documentation"           doc/index 	       doc       />
 <nav:but 3party         "3rd Party Docs"          3party                        />
 <nav:but doc_mrtg-forum "Mailinglists"            support/index                      />
 <nav:but trac           "Bug Reports, Wiki"       http://oss.oetiker.ch/mrtg-trac/ />
 <nav:but sponsor        "Project Sponsors"        sponsor                       />
 <nav:but cast           "Cast" 	           cast/index                         />
</nav:bar>

<nav:bar 1 doc           "doc/">
#include "doc/navbar.inc"
</nav:bar>
